"""Local pre-generated audio cache for fixed fast-command acknowledgements.

Fast-command acknowledgements ("He subido el volumen.", "Abriendo.") are drawn
from a small fixed vocabulary. Synthesizing them through a remote TTS provider
on every turn adds a full round trip to the fastest, most latency-sensitive
path in the runtime for no benefit: the audio never changes. This cache stores
pre-generated bytes for known ack text and is checked before any TTS provider
call; a miss falls through to the configured provider unchanged.

Cache files are generated offline (see ``scripts/generate_ack_cache.py``) by an
operator with a real TTS provider configured; this module only reads them.
"""

from __future__ import annotations

import hashlib
from pathlib import Path
from typing import AsyncIterator


def cache_key(text: str) -> str:
    """Stable filename-safe key for one acknowledgement string."""
    return hashlib.sha256(text.strip().encode("utf-8")).hexdigest()[:16]


class AckAudioCache:
    """Read-only lookup of pre-generated audio for known acknowledgement text."""

    def __init__(self, cache_dir: Path | str, *, extension: str = "wav") -> None:
        self._dir = Path(cache_dir)
        self._extension = extension.lstrip(".")
        self._loaded: dict[str, bytes] = {}

    def get(self, text: str) -> bytes | None:
        """Return cached audio bytes for *text*, or None on a miss."""
        normalized = (text or "").strip()
        if not normalized:
            return None
        if normalized in self._loaded:
            return self._loaded[normalized]
        path = self._dir / f"{cache_key(normalized)}.{self._extension}"
        try:
            data = path.read_bytes()
        except OSError:
            return None
        self._loaded[normalized] = data
        return data


async def bytes_to_stream(data: bytes) -> AsyncIterator[bytes]:
    """Wrap already-synthesized audio bytes as a one-shot async byte stream."""
    yield data
