"""Local pre-generated audio cache for fixed fast-command acknowledgements.

Fast-command acknowledgements ("He subido el volumen.", "Abriendo la aplicación.") are drawn
from a small fixed vocabulary. Synthesizing them through a remote TTS provider
on every turn adds a full round trip to the fastest, most latency-sensitive
path in the runtime for no benefit: the audio never changes. This cache stores
pre-generated bytes for known ack text and is checked before any TTS provider
call; a miss falls through to the configured provider unchanged.

Cache files are generated offline (see ``scripts/generate_ack_cache.py``) by an
operator with a real TTS provider configured; this module only reads them.
"""

from __future__ import annotations

import hashlib
from pathlib import Path
from typing import AsyncIterator


def cache_key(text: str) -> str:
    """Stable filename-safe key for one acknowledgement string."""
    return hashlib.sha256(text.strip().encode("utf-8")).hexdigest()[:16]


class AckAudioCache:
    """Read-only lookup of pre-generated audio for known acknowledgement text."""

    def __init__(self, cache_dir: Path | str, *, extension: str = "wav") -> None:
        self._dir = Path(cache_dir)
        self._extension = extension.lstrip(".")
        self._loaded: dict[str, bytes] = {}

    def get(self, text: str) -> bytes | None:
        """Return cached audio bytes for *text*, or None on a miss."""
        normalized = (text or "").strip()
        if not normalized:
            return None
        if normalized in self._loaded:
            return self._loaded[normalized]
        path = self._dir / f"{cache_key(normalized)}.{self._extension}"
        try:
            data = path.read_bytes()
        except OSError:
            return None
        self._loaded[normalized] = data
        return data

    def put(self, text: str, data: bytes) -> None:
        """Store audio for *text* (used for the cloned-voice startup welcome)."""
        normalized = (text or "").strip()
        self._dir.mkdir(parents=True, exist_ok=True)
        path = self._dir / f"{cache_key(normalized)}.{self._extension}"
        tmp = path.with_suffix(".tmp")
        tmp.write_bytes(data)
        tmp.replace(path)
        self._loaded[normalized] = data


def join_wavs(chunks: list[bytes]) -> bytes:
    """Concatenate same-format WAV chunks (a streamed synthesis) into one WAV."""
    import io  # noqa: PLC0415
    import wave  # noqa: PLC0415

    frames, params = [], None
    for chunk in chunks:
        with wave.open(io.BytesIO(chunk), "rb") as wav:
            params = params or wav.getparams()
            frames.append(wav.readframes(wav.getnframes()))
    buffer = io.BytesIO()
    with wave.open(buffer, "wb") as out:
        out.setparams(params)
        out.writeframes(b"".join(frames))
    return buffer.getvalue()


async def bytes_to_stream(data: bytes) -> AsyncIterator[bytes]:
    """Wrap already-synthesized audio bytes as a one-shot async byte stream."""
    yield data
